- .eslintrc.js
- .travis.yml
- package.json
- shared/components/map.js
- shared/containers/mapLayout.js
- shared/reducers/map.js
added eslint and fixed warning and error.
just it
> added eslint and warning fix

- ios/Goober/Images.xcassets/AppIcon.appiconset/Contents.json
- package.json
- shared/actions/mapActions.js
- shared/components/CameraView.js
- shared/components/EventList.js
- shared/components/ListWrapper.js
- shared/components/map.js
- shared/containers/app.js
- shared/containers/mapLayout.js
- shared/reducers/index.js
- shared/store.js
seperate map-component and map-container clearly.
And create store.js to manage code clearly.
> structure for container and component and store

- ios/Goober.xcodeproj/project.pbxproj
- package.json
- shared/actions/actionTypes.js
- shared/actions/mapActions.js
- shared/components/map.js
- shared/containers/mapLayout.js
- shared/reducers/map.js
implemented "action - reducer - state" in right form.
this PR is to unify applying "action - reducer - state" style.
> Action on map

- android/app/src/main/java/com/gooberproject/MainApplication.java
fix build error ':app:compileDebugJavaWithJavac'
> fix android build error

- __tests__/map-test.js
- shared/actions/actionTypes.js
- shared/actions/mapActions.js
- shared/components/map.js
- shared/containers/mapLayout.js
- shared/reducers/map.js
implemented map marker, and connect to server.
which means, it fetch markers data from server and display to map.
> Map marker

- index.ios.js
- ios/GooberProject.xcodeproj/project.pbxproj
- ios/GooberProject.xcodeproj/xcshareddata/xcschemes/GooberProject.xcscheme
- ios/GooberProject/Base.lproj/LaunchScreen.xib
- ios/GooberProject/Images.xcassets/AppIcon.appiconset/Contents.json
- ios/GooberProject/Info.plist
- ios/GooberProjectTests/Info.plist
- package.json
- shared/components/CameraView.js
- shared/components/CreateForm.js
I've created to component for creating event to the server.
It should be binding data from map data into this component.
> first Post data to server

- shared/actions/actionTypes.js
- shared/actions/mapActions.js
- shared/components/ListWrapper.js
- shared/components/headerbox.js
- shared/components/map.js
- shared/components/mapCard.js
- shared/containers/headerLayout.js
- shared/containers/mapLayout.js
- shared/reducers/map.js
For list data structure, there is ".filter" method.
So I replaced previous filter function to above given method.
> replace previous filter function to  .filter func

- __tests__/header-test.js
- __tests__/map-test.js
- index.ios.js
- shared/actions/actionTypes.js
- shared/actions/mapActions.js
- shared/components/headerbox.js
- shared/components/map.js
- shared/containers/headerLayout.js
- shared/containers/mapLayout.js
- shared/reducers/map.js
change variable name to sync with data schema.
* markers => items       (since,  marker is one property of item)
* update_marker => categorizeItem
> change variable name to sync up with data schema

- shared/components/CreateForm.js
I've complete to get address func from geodata with geocoding APi.
> complete to getaddress from geodata

- shared/components/map.js
- shared/containers/mapLayout.js
- shared/reducers/map.js
connect back-end via get api and sync data schema for items.
> Marker and card

- shared/components/Card.js
- shared/components/MapButton.js
- shared/components/map.js
- shared/components/sceneInitial.js
1. add location and camera button. 
(clicking location button => should go current location)
2. some styling
> Add location and camera button

- shared/components/headerbox.js
> fix design bug for ios

- shared/components/Card.js
- shared/components/EventList.js
- shared/components/map.js
- shared/containers/listLayout.js
- shared/containers/mapLayout.js
- shared/reducers/map.js
* Remove cardVisible
* Edit onRegionChangeComplete
> Remove cardVisible

- shared/components/CreateForm.js
- shared/containers/formLayout.js
complete to figuring out hotfix stuff on create-form
> hotfix completed

- shared/components/Card.js
> add card style

- __tests__/map-test.js
- shared/actions/actionTypes.js
- shared/actions/listActions.js
- shared/actions/mapActions.js
- shared/components/EventList.js
- shared/components/map.js
- shared/containers/listLayout.js
- shared/containers/mapLayout.js
- shared/reducers/map.js
change query using in list, and apply redux
> change get query and apply redux to get zoom level

- shared/components/CreateForm.js
> simple styling for createForm

- package.json
change react-native-maps version to fix ios bug
> change react-native-maps version to fix ios bug

- shared/components/map.js
- shared/reducers/map.js
* Edit map component
* Edit map reducer
> Add card hide function

- shared/components/map.js
* Add prev* variable
* Add componentWillMount for setting current location at launch time
Fetching data from server is related with lat lng and zoom level not just map move event.
> Change marker fetching time

- shared/components/LogInFacebook.js
- update permission to 'email' and 'user_about_me'
> Update facebook permission

- shared/components/Card.js
- shared/components/MainHeader.js
fixed blank issue on the bottom of the card shown on the map scene and added shadow on the main header
> fixed style

- package.json
- shared/components/initialScene.js
giving flex on the swiper's wrapper component was the reason.
> fixed swiper render not showing problem on iOS

- shared/actions/actionTypes.js
- shared/actions/mapActions.js
- shared/actions/myPageActions.js
- shared/components/CameraView.js
- shared/components/Card.js
- shared/components/Create.js
- shared/components/MainHeader.js
- shared/components/MapButton.js
- shared/components/Setting.js
- shared/components/detailHeader.js
- shared/components/detailLitemap.js
- shared/components/detailView.js
- shared/components/eventReportView.js
- shared/components/initialScene.js
- shared/components/map.js
- shared/components/myPage.js
- shared/components/smallHeader.js
- shared/containers/myPageLayout.js
- shared/reducers/myPage.js
- shared/utils.js
Add favorite event function.
And now, you can see your favorite event in my page view!
> Favorite event

- shared/actions/authActions.js
- shared/actions/listActions.js
- shared/actions/mapActions.js
- shared/actions/myPageActions.js
- shared/utils.js
- added default http header and replaced all previous hardcoded codes.
> Added default http headers

- shared/utils.js
- it was using swallow copy. so I replaced it to use deep copy.
> change getAuthHeaders functions to use deep copy

- shared/components/Card.js
- shared/components/detailView.js
change format
ex) 2:5 -> 02: 05
> fix date bug in card

- shared/actions/authActions.js
- shared/services/authService.js
- shared/services/imageService.js
- shared/services/itemService.js
- shared/services/userService.js
> add rest api services

- shared/containers/allLayout.js
- shared/containers/loginFacebookLayout.js
> update import file name

- shared/utils.js
- this is just for the trello integration test.
> remove comment

- package.json
> Add lint command

- shared/containers/allLayout.js
- now, user can exit pingo app if they press back button at the map scene.
> add exit android app

- shared/containers/allLayout.js
- updated react-native-router-flux config to use constants.
> update router config
